In [48]:
import numpy as np
import time

In [2]:
arr = np.arange(1,9)
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [3]:
type(arr)

numpy.ndarray

In [4]:
arr1 = np.arange(1,10,2)
arr1


array([1, 3, 5, 7, 9])

In [5]:
arr1[2]

5

In [8]:
arr2 = np.array([[1,2,3],[4,5,6]])

In [9]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
arr3 =  np.zeros((2,3))

In [16]:
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [18]:
arr3 = np.zeros((2,3,4))
arr3

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [20]:
arr4 = np.identity(4)
arr4

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [40]:
arr5 = np.ones((2,3,3))
arr5

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [24]:
arr6 = np.linspace(0,10,5)
arr6

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [25]:
arr8 = arr1.copy()
arr8

array([1, 3, 5, 7, 9])

In [26]:
arr1

array([1, 3, 5, 7, 9])

In [28]:
arr8[3] = 88
arr8

array([ 1,  3,  5, 88,  9])

In [29]:
arr1

array([1, 3, 5, 7, 9])

In [37]:
arr5.shape

(2, 3, 2)

In [41]:
arr5.ndim

3

In [42]:
arr9 = np.ones((2,3,4,2))
arr9

array([[[[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]]],


       [[[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]]]])

In [45]:
arr9.ndim

4

In [47]:
arr5

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [46]:
arr5.size

18

## Numpy vs List

In [56]:
# list

x = list(range(1000000))
y = list(range(1000000,2000000))

start_time = time.time()

res = [x+y for x,y in zip(x,y)]

print(time.time()-start_time)

0.4879882335662842


In [ ]:
x = np.arange(1000000)
y = np.arange(1000000,2000000))

start_time = time.time()

res = [x+y for x,y in zip(x,y)]

print(time.time()-start_time)